OPENAI_API_KEY=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
TAVILY_API_KEY=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
LANGCHAIN_API_KEY=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
LANGCHAIN_TRACING_V2=true
LANGCHAIN_PROJECT=research-agent